-- =====================================================================
-- Lobby · Supabase schema
-- Run this in the Supabase SQL Editor (or via `supabase db push`).
--
-- SECURITY MODEL (read this before changing anything):
-- This app has no user authentication — a display name and a room link
-- are the only "identity". That means there is no authenticated Supabase
-- user to write RLS policies against, so the safe pattern is:
--
--   * RLS is ENABLED on every table
--   * NO public policies are granted (anon/authenticated roles get nothing)
--   * apps/api connects with the SERVICE_ROLE key, which bypasses RLS
--   * apps/web NEVER talks to Supabase directly — all DB access goes
--     through NestJS, which enforces "do you know the channel id?"
--
-- Do NOT put the service_role key in the Angular app or any client-side
-- env file. It bypasses every policy below. It belongs only in the
-- NestJS server environment.
-- =====================================================================


-- ---------------------------------------------------------------------
-- channels
-- ---------------------------------------------------------------------
create table if not exists public.channels (
  -- nanoid generated by NestJS, not a uuid — it's the shareable room code
  id          text primary key,
  name        text not null check (char_length(name) between 1 and 60),
  created_at  timestamptz not null default now(),
  -- rooms expire automatically; null means "no expiry"
  expires_at  timestamptz
);

comment on table  public.channels        is 'A chat room. The id doubles as the shareable room code.';
comment on column public.channels.id     is 'nanoid from NestJS (e.g. LBY-7X3Q) — used directly in the invite link.';
comment on column public.channels.expires_at is 'When the room and its messages should be considered dead. Null = never.';

create index if not exists channels_expires_at_idx
  on public.channels (expires_at)
  where expires_at is not null;


-- ---------------------------------------------------------------------
-- messages
-- ---------------------------------------------------------------------
create table if not exists public.messages (
  id          uuid primary key default gen_random_uuid(),
  channel_id  text not null references public.channels(id) on delete cascade,
  -- display name only; there is no users table because there is no auth
  author_name text not null check (char_length(author_name) between 1 and 40),
  text        text not null check (char_length(text) between 1 and 2000),
  created_at  timestamptz not null default now()
);

comment on table  public.messages             is 'Chat messages. Deleted automatically when the parent channel is deleted.';
comment on column public.messages.author_name is 'Display name at send time. Not a foreign key — this app has no user accounts.';

-- The only query the app makes: "messages for this channel, oldest first"
create index if not exists messages_channel_created_idx
  on public.messages (channel_id, created_at);


-- ---------------------------------------------------------------------
-- user_profiles
-- ---------------------------------------------------------------------
create table if not exists public.user_profiles (
  user_id      text primary key,
  display_name text not null check (char_length(display_name) between 1 and 40),
  bio          text check (char_length(bio) <= 280),
  avatar_url   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.user_profiles is 'User profile records for authenticated account flows.';
comment on column public.user_profiles.user_id is 'Stable account identifier used by app-level profile routes.';

create or replace function public.set_updated_at_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists user_profiles_set_updated_at on public.user_profiles;
create trigger user_profiles_set_updated_at
before update on public.user_profiles
for each row
execute function public.set_updated_at_timestamp();


-- ---------------------------------------------------------------------
-- account_settings
-- ---------------------------------------------------------------------
create table if not exists public.account_settings (
  user_id                      text primary key,
  email_notifications_enabled boolean not null default true,
  push_notifications_enabled  boolean not null default true,
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now()
);

comment on table public.account_settings is 'Account settings persisted for backend account-management flows.';

create trigger account_settings_set_updated_at
before update on public.account_settings
for each row
execute function public.set_updated_at_timestamp();


-- ---------------------------------------------------------------------
-- Row Level Security
-- Enabled with no policies: anon and authenticated roles can do nothing.
-- apps/api uses the service_role key and bypasses this entirely.
-- ---------------------------------------------------------------------
alter table public.channels enable row level security;
alter table public.messages enable row level security;
alter table public.user_profiles enable row level security;
alter table public.account_settings enable row level security;


-- ---------------------------------------------------------------------
-- Optional: expired-room cleanup
-- Call this from a Supabase scheduled job, or just run it manually.
-- Messages go with the channel via the on delete cascade above.
-- ---------------------------------------------------------------------
create or replace function public.delete_expired_channels()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.channels
  where expires_at is not null
    and expires_at < now();
$$;
