-- =====================================================================
-- Lobby · Supabase schema
-- Run this in the Supabase SQL Editor (or via `supabase db push`).
--
-- SECURITY MODEL (read this before changing anything):
-- This app has no user authentication — a display name and a room link
-- are the only "identity". That means there is no authenticated Supabase
-- user to write RLS policies against, so the safe pattern is:
--
--   * RLS is ENABLED on every table
--   * NO public policies are granted (anon/authenticated roles get nothing)
--   * apps/api connects with the SERVICE_ROLE key, which bypasses RLS
--   * apps/web NEVER talks to Supabase directly — all DB access goes
--     through NestJS, which enforces "do you know the channel id?"
--
-- Do NOT put the service_role key in the Angular app or any client-side
-- env file. It bypasses every policy below. It belongs only in the
-- NestJS server environment.
-- =====================================================================


-- ---------------------------------------------------------------------
-- channels
-- ---------------------------------------------------------------------
create table if not exists public.channels (
  -- nanoid generated by NestJS, not a uuid — it's the shareable room code
  id          text primary key,
  name        text not null check (char_length(name) between 1 and 60),
  created_at  timestamptz not null default now(),
  -- rooms expire automatically; null means "no expiry"
  expires_at  timestamptz
);

comment on table  public.channels        is 'A chat room. The id doubles as the shareable room code.';
comment on column public.channels.id     is 'nanoid from NestJS (e.g. LBY-7X3Q) — used directly in the invite link.';
comment on column public.channels.expires_at is 'When the room and its messages should be considered dead. Null = never.';

create index if not exists channels_expires_at_idx
  on public.channels (expires_at)
  where expires_at is not null;


-- ---------------------------------------------------------------------
-- messages
-- ---------------------------------------------------------------------
create table if not exists public.messages (
  id          uuid primary key default gen_random_uuid(),
  channel_id  text not null references public.channels(id) on delete cascade,
  -- display name only; there is no users table because there is no auth
  author_name text not null check (char_length(author_name) between 1 and 40),
  text        text not null check (char_length(text) between 1 and 2000),
  created_at  timestamptz not null default now()
);

comment on table  public.messages             is 'Chat messages. Deleted automatically when the parent channel is deleted.';
comment on column public.messages.author_name is 'Display name at send time. Not a foreign key — this app has no user accounts.';

-- The only query the app makes: "messages for this channel, oldest first"
create index if not exists messages_channel_created_idx
  on public.messages (channel_id, created_at);


-- ---------------------------------------------------------------------
-- Row Level Security
-- Enabled with no policies: anon and authenticated roles can do nothing.
-- apps/api uses the service_role key and bypasses this entirely.
-- ---------------------------------------------------------------------
alter table public.channels enable row level security;
alter table public.messages enable row level security;


-- ---------------------------------------------------------------------
-- Optional: expired-room cleanup
-- Call this from a Supabase scheduled job, or just run it manually.
-- Messages go with the channel via the on delete cascade above.
-- ---------------------------------------------------------------------
create or replace function public.delete_expired_channels()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.channels
  where expires_at is not null
    and expires_at < now();
$$;
