import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import {
  LucideArrowRight,
  LucideBell,
  LucideBookmark,
  LucideCamera,
  LucideCheck,
  LucideChevronDown,
  LucideChevronsUpDown,
  LucideCopy,
  LucideCrown,
  LucideEye,
  LucideEyeOff,
  LucideMaximize2,
  LucideHash,
  LucideInfo,
  LucideLayoutGrid,
  LucideLink,
  LucideLogOut,
  LucideLock,
  LucideMenu,
  LucideMessageCircle,
  LucideMic,
  LucideMicOff,
  LucideMinimize2,
  LucideMoreVertical,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePanelRightClose,
  LucidePanelRightOpen,
  LucidePencil,
  LucidePhone,
  LucidePhoneOff,
  LucidePlus,
  LucideRefreshCw,
  LucideReply,
  LucideScreenShare,
  LucideScreenShareOff,
  LucideSearch,
  LucideSend,
  LucideSettings,
  LucideShuffle,
  LucideSmile,
  LucideTrash2,
  LucideTriangleAlert,
  LucideUser,
  LucideUserMinus,
  LucideUserPlus,
  LucideUsers,
  LucideVolume2,
  LucideX,
  LucideDynamicIcon,
} from '@lucide/angular';

const LOBBY_ICONS = {
  'arrow-right': LucideArrowRight,
  bell: LucideBell,
  bookmark: LucideBookmark,
  camera: LucideCamera,
  check: LucideCheck,
  'chevron-down': LucideChevronDown,
  'chevrons-up-down': LucideChevronsUpDown,
  copy: LucideCopy,
  crown: LucideCrown,
  eye: LucideEye,
  'eye-off': LucideEyeOff,
  expand: LucideMaximize2,
  hash: LucideHash,
  info: LucideInfo,
  'layout-grid': LucideLayoutGrid,
  link: LucideLink,
  logout: LucideLogOut,
  lock: LucideLock,
  menu: LucideMenu,
  chat: LucideMessageCircle,
  mic: LucideMic,
  'mic-off': LucideMicOff,
  minimize: LucideMinimize2,
  'more-vertical': LucideMoreVertical,
  'panel-close': LucidePanelRightClose,
  'panel-open': LucidePanelRightOpen,
  'panel-left-close': LucidePanelLeftClose,
  'panel-left-open': LucidePanelLeftOpen,
  edit: LucidePencil,
  call: LucidePhone,
  'leave-call': LucidePhoneOff,
  plus: LucidePlus,
  refresh: LucideRefreshCw,
  reply: LucideReply,
  'screen-share': LucideScreenShare,
  'screen-share-off': LucideScreenShareOff,
  search: LucideSearch,
  send: LucideSend,
  settings: LucideSettings,
  shuffle: LucideShuffle,
  smile: LucideSmile,
  delete: LucideTrash2,
  warning: LucideTriangleAlert,
  user: LucideUser,
  'user-minus': LucideUserMinus,
  'user-plus': LucideUserPlus,
  users: LucideUsers,
  'volume-2': LucideVolume2,
  close: LucideX,
} as const;

export type LobbyIconName = keyof typeof LOBBY_ICONS;

@Component({
  selector: 'app-icon',
  standalone: true,
  imports: [LucideDynamicIcon],
  template: `<svg [lucideIcon]="icon()" [size]="size()" [strokeWidth]="strokeWidth()"></svg>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: 'inline-flex shrink-0 items-center justify-center leading-none',
  },
})
export class LobbyIconComponent {
  name = input.required<LobbyIconName>();
  size = input<number>(10);
  strokeWidth = input<number>(1.8);

  protected readonly icon = computed(() => LOBBY_ICONS[this.name()]);
}
